### ISSUE TITLE
how create tags?

### ISSUE THREAD

**Issue by samatzp** [DucDao0906/Demo_App#2]

**Comment by DucDa0** [comment]
Just type your own tag in Write Post page, this will create tag automatically.
Tag function is quite simple and not full function, I haven't completed it yet, if you want to show your created tag in Tag Page and customize color for it, let use Postman and add some tags:
> API Url: https://mydevcomm.herokuapp.com/api/tags
```
{
"tagName":"Your tag name",
"tagColor":"Hex color code",
"isPopular": true // set true to show in Tag page
}
```
